/**
 * Chat domain types for user-facing chat feature
 *
 * Organized to mirror backend schemas/chat.py for easy cross-reference.
 *
 * This module contains:
 * - Core types: MessageRole, Message, Conversation (matching backend schemas/chat.py)
 * - Interaction types: SuggestedValue, SuggestedAction, etc.
 * - Stream event types for SSE streaming
 * - UI-specific types: ChatMessage (for display)
 */

// ============================================================================
// Core Types (matching backend models)
// ============================================================================

export type MessageRole = 'user' | 'assistant' | 'system';

export interface Conversation {
    id: number;
    user_id?: number;
    title?: string;
    created_at: string;
    updated_at: string;
}


// ============================================================================
// Interaction Types
// ============================================================================

export enum InteractionType {
    TEXT_INPUT = 'text_input',
    VALUE_SELECTED = 'value_selected',
    ACTION_EXECUTED = 'action_executed'
}

export interface SuggestedValue {
    label: string;
    value: string;
}

export interface SuggestedAction {
    label: string;
    action: string;
    handler: 'client' | 'server';
    data?: unknown;
    style?: 'primary' | 'secondary' | 'warning';
}

export interface CustomPayload {
    type: string;
    data: unknown;
}

export interface ToolHistoryEntry {
    tool_name: string;
    input: Record<string, unknown>;
    output: string | Record<string, unknown>;
}


// ============================================================================
// Agent Trace Types (comprehensive execution tracing)
// ============================================================================

export interface ToolDefinition {
    name: string;
    description: string;
    input_schema: Record<string, unknown>;
}

export interface TokenUsage {
    input_tokens: number;
    output_tokens: number;
}

export interface ToolCall {
    tool_use_id: string;
    tool_name: string;
    /** What model requested and tool received (no transform) */
    tool_input: Record<string, unknown>;
    /** What executor returned (raw, before formatting) */
    output_from_executor: unknown;
    output_type: string;
    /** What went into tool_result message back to model */
    output_to_model: string;
    /** Payload generated by this tool call (if any) */
    payload?: Record<string, unknown>;
    execution_ms: number;
}

export interface AgentIteration {
    iteration: number;
    /** EXACT messages array sent to model */
    messages_to_model: Record<string, unknown>[];
    /** Model response content blocks */
    response_content: Record<string, unknown>[];
    stop_reason: string;
    usage: TokenUsage;
    api_call_ms: number;
    tool_calls: ToolCall[];
}

export interface FinalResponse {
    message: string;
    suggested_values?: SuggestedValue[];
    suggested_actions?: SuggestedAction[];
    custom_payload?: CustomPayload;
    tool_history?: ToolHistoryEntry[];
    conversation_id?: number;
}

export interface AgentTrace {
    trace_id: string;

    // Configuration
    model: string;
    max_tokens: number;
    max_iterations: number;
    temperature: number;
    system_prompt: string;
    tools: ToolDefinition[];
    context: Record<string, unknown>;

    // Input - the stored conversation (before tool exchange)
    initial_messages: Record<string, unknown>[];

    // Execution
    iterations: AgentIteration[];

    // Outcome
    final_text: string;
    total_iterations: number;
    outcome: 'complete' | 'max_iterations' | 'cancelled' | 'error';
    error_message?: string;

    // Final response (what was sent to frontend)
    final_response?: FinalResponse;

    // Metrics (cumulative across all iterations, for cost tracking)
    total_input_tokens: number;
    total_output_tokens: number;
    total_duration_ms: number;
    // High-water mark: largest single API call's input tokens (context window pressure)
    peak_input_tokens?: number;
}

/** @deprecated Use AgentTrace instead - kept for backwards compatibility */
export type ChatDiagnostics = AgentTrace;

export interface ActionMetadata {
    action_identifier: string;
    action_data?: unknown;
}


// ============================================================================
// Message Types (depends on interaction types above)
// ============================================================================

export interface MessageExtras {
    tool_history?: ToolHistoryEntry[];
    custom_payload?: CustomPayload;
    trace?: AgentTrace;  // Full execution trace
    diagnostics?: AgentTrace;  // Alias for backwards compatibility
    suggested_values?: SuggestedValue[];
    suggested_actions?: SuggestedAction[];
}

export interface Message {
    id: number;
    conversation_id?: number;
    role: MessageRole;
    content: string;
    context?: Record<string, unknown>;
    extras?: MessageExtras;
    created_at: string;
}

export interface ConversationWithMessages extends Conversation {
    messages: Message[];
}


// ============================================================================
// Stream Event Types (discriminated union with explicit 'type' field)
// ============================================================================

export interface TextDeltaEvent {
    type: 'text_delta';
    text: string;
}

export interface StatusEvent {
    type: 'status';
    message: string;
}

export interface ToolStartEvent {
    type: 'tool_start';
    tool: string;
    input: unknown;
    tool_use_id: string;
}

export interface ToolProgressEvent {
    type: 'tool_progress';
    tool: string;
    stage: string;
    message: string;
    progress: number;  // 0.0 to 1.0
    data?: unknown;
}

export interface ToolCompleteEvent {
    type: 'tool_complete';
    tool: string;
    index: number;
}

export interface CompleteEvent {
    type: 'complete';
    payload: ChatResponsePayload;
}

export interface ErrorEvent {
    type: 'error';
    message: string;
}

export interface CancelledEvent {
    type: 'cancelled';
}

export type StreamEvent =
    | TextDeltaEvent
    | StatusEvent
    | ToolStartEvent
    | ToolProgressEvent
    | ToolCompleteEvent
    | CompleteEvent
    | ErrorEvent
    | CancelledEvent;


// ============================================================================
// Response Payload
// ============================================================================

export interface ChatResponsePayload {
    message: string;
    suggested_values?: SuggestedValue[];
    suggested_actions?: SuggestedAction[];
    custom_payload?: CustomPayload;
    tool_history?: ToolHistoryEntry[];
    conversation_id?: number;
    warning?: string;
    diagnostics?: ChatDiagnostics;
}


// ============================================================================
// UI-Specific Types
// ============================================================================

/**
 * Chat message for UI display (includes interaction elements)
 */
export interface ChatMessage {
    role: 'user' | 'assistant';
    content: string;
    timestamp: string;
    suggested_values?: SuggestedValue[];
    suggested_actions?: SuggestedAction[];
    custom_payload?: CustomPayload;
    tool_history?: ToolHistoryEntry[];
    warning?: string;
    diagnostics?: ChatDiagnostics;
}

/**
 * Payload handler for custom chat payloads
 */
export interface PayloadHandler {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    render: (payload: any, callbacks: { onAccept?: (data: any) => void; onReject?: () => void }) => React.ReactNode;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    onAccept?: (payload: any, pageState?: any) => void;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    onReject?: (payload: any) => void;
    renderOptions?: {
        panelWidth?: string;
        headerTitle?: string;
        headerIcon?: string;
    };
}


// ============================================================================
// Backwards Compatibility Aliases
// ============================================================================

/** @deprecated Use ChatMessage instead */
export type GeneralChatMessage = ChatMessage;
